client1=paramiko.SSHClient()
client1.set_missing_host_key_policy(paramiko.AutoAddPolicy())
logging.info("OA IP : " +str(ip_addr))
client1.connect(str(ip_addr), username = str(username), password = str(password))
time.sleep(1)
remoteConnection =client1.invoke_shell()
time.sleep(1)
remoteConnection.send("df\n")
client1.close()
